// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqjvbtoignmzwwdqzwyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxanZidG9pZ25tend3ZHF6d3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NzQxNzYsImV4cCI6MjA3NzI1MDE3Nn0.p5nZ5WTpH7eo4N8EkaWobAnWr_jYX9HDpMa0Vsar1xQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});